# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2fdd6eb03819137c520ff13a721fc0a2d5351ef081ba81e96c4ee8e02319542a3f812ecaf4b25b663d640d552b3d67e8be6c43833e801ff18c0373f9108e44a7

test:
  secret_key_base: c6cb6be9e502762cb4d4d15a2a45ea55be4fb53aaa28f8b8e957e759f789212b81709d7ff4cc3bba0bdb2b63a44e4c246579001241646eaa006cb8a3d0a3478f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
